### ISSUE TITLE
Readme questions

### ISSUE THREAD

**Issue by Seanforfun** [rwenqi/GFN-dehazing#1]
Hi Wenqi,
    I am really interesting to your code and want to run it. However, in you README.md, I didn't find the command that you mentioned. Please provide the commands to me if possible.
   Thank you!

![screen shot for readme](https://i.imgur.com/tiLIocf.png)

**Comment by rwenqi** [comment]
You can run the "demo_test" for testing your images.

**Comment by rwenqi** [comment]
You can run the "demo_test" for testing your images.
