### ISSUE TITLE
运行demo_test.m出现如下问题，求教。

### ISSUE THREAD

**Issue by GY5134** [rwenqi/GFN-dehazing#5]
未定义变量 "caffe" 或类 "caffe.reset_all"。
出错 demo_test (line 4)
caffe.reset_all(); 
出错地方“caffe.reset_all();”
请问，如何解决此问题？

**Comment by GY5134** [comment]
谢谢任老师，我已近搞定了。

**Comment by zkh123456789** [comment]
兄弟  我想拿自己的数据集重新训练测试   请问应该怎么做，求指导

**Comment by GY5134** [comment]
> 兄弟 我想拿自己的数据集重新训练测试 请问应该怎么做，求指导

请参考这个博客，https://www.cnblogs.com/wxl845235800/p/10599265.html

**Comment by zkh123456789** [comment]
非常感谢&nbsp; &nbsp; ！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yingao"<notifications@github.com&gt;; 
发送时间: 2020年7月3日(星期五) 下午5:00
收件人: "rwenqi/GFN-dehazing"<GFN-dehazing@noreply.github.com&gt;; 
抄送: "赵康辉"<578969495@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [rwenqi/GFN-dehazing] 运行demo_test.m出现如下问题，求教。 (#5)





  
兄弟 我想拿自己的数据集重新训练测试 请问应该怎么做，求指导
  
请参考这个博客，https://www.cnblogs.com/wxl845235800/p/10599265.html

**Comment by 940152691** [comment]
您好，请问这个模型可以用自己的数据重新训练吗？还是只能测试？

**Comment by GY5134** [comment]
我是测试用，谢谢。

**Comment by xiaomei-0217** [comment]
> 未定义变量 "caffe" 或类 "caffe.reset_all"。
> 出错 demo_test (line 4)
> caffe.reset_all();
> 出错地方“caffe.reset_all();”
> 请问，如何解决此问题？
您好，我现在也遇到了同样的问题，请教一下您怎么解决的，我也是用于测试的

**Comment by GY5134** [comment]
系统路径没有配置好，参考上面的网址就可以顺利运行测试。

**Comment by GY5134** [comment]
> > 未定义变量 "caffe" 或类 "caffe.reset_all"。
> > 出错 demo_test (line 4)
> > caffe.reset_all();
> > 出错地方“caffe.reset_all();”
> > 请问，如何解决此问题？
> > 您好，我现在也遇到了同样的问题，请教一下您怎么解决的，我也是用于测试的

**Comment by xiaomei-0217** [comment]
> 系统路径没有配置好，参考上面的网址就可以顺利运行测试。

好的，谢谢您

**Comment by kumarballapavan** [comment]
Undefined variable "caffe" or class "caffe.reset_all". How to resolve this issue?

**Comment by GY5134** [comment]
Please refer to this blog，https://www.cnblogs.com/wxl845235800/p/10599265.html 。You should configure the Matlab interface in Caffe.
